logging:
  file:
    name: log/CDCSonCNN-dev.log
  level:
    cn.doublefloat.CDCSonCNN: debug
    org.springframework: warn


project:
  path: /Users/liguangshuai/Desktop/CDCSonCNN/project/

docker:
  url: "39.107.70.247"
  port: 2375
  certsPath: /Users/liguangshuai/Desktop/CDCSonCNN/certs